//
// Fats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Fats: Codable, JSONEncodable, Hashable {

    /** Saturated fat measured in gram */
    public var saturatedFat: Double?
    /** Butyric acid measured in gram */
    public var butyricAcid: Double?
    /** Caproic acid measured in gram */
    public var caproicAcid: Double?
    /** Caprylic acid measured in gram */
    public var caprylicAcid: Double?
    /** Capric acid measured in gram */
    public var capricAcid: Double?
    /** Lauric acid measured in gram */
    public var lauricAcid: Double?
    /** Myristic acid measured in gram */
    public var myristicAcid: Double?
    /** Palmitic acid measured in gram */
    public var palmiticAcid: Double?
    /** Stearic acid measured in gram */
    public var stearicAcid: Double?
    /** Arachidic acid measured in gram */
    public var arachidicAcid: Double?
    /** Behenic acid measured in gram */
    public var behenicAcid: Double?
    /** Lignoceric acid measured in gram */
    public var lignocericAcid: Double?
    /** Cerotic acid measured in gram */
    public var ceroticAcid: Double?
    /** Montanic acid measured in gram */
    public var montanicAcid: Double?
    /** Melissic acid measured in gram */
    public var melissicAcid: Double?
    /** Monounsaturated fat measured in gram */
    public var monounsaturatedFat: Double?
    /** Polyunsaturated fat measured in gram */
    public var polyunsaturatedFat: Double?
    /** Alpha linolenic acid measured in gram */
    public var alphaLinolenicAcid: Double?
    /** Eicosapentaenoic acid measured in gram */
    public var eicosapentaenoicAcid: Double?
    /** Docosahexaenoic acid measured in gram */
    public var docosahexaenoicAcid: Double?
    /** Omega 3 fat measured in gram */
    public var omega3Fat: Double?
    /** Omega 6 fat measured in gram */
    public var omega6Fat: Double?
    /** Omega 9 fat measured in gram */
    public var omega9Fat: Double?
    /** Arachidonic acid measured in gram */
    public var arachidonicAcid: Double?
    /** Gamma linolenic acid measured in gram */
    public var gammaLinolenicAcid: Double?
    /** Dihomo gamma linolenic acid measured in gram */
    public var dihomoGammaLinolenicAcid: Double?
    /** Linoleic Acid measured in gram */
    public var linoleicAcid: Double?
    /** Oleic Acid measured in gram */
    public var oleicAcid: Double?
    /** Trans fat measured in gram */
    public var transFat: Double?
    /** Cholesterol measured in gram */
    public var cholesterol: Double?
    /** Elaidic acid measured in gram */
    public var elaidicAcid: Double?
    /** Gondoic acid measured in gram */
    public var gondoicAcid: Double?
    /** Mead acid measured in gram */
    public var meadAcid: Double?
    /** Erucic acid measured in gram */
    public var erucicAcid: Double?
    /** Nervonic acid measured in gram */
    public var nervonicAcid: Double?

    public init(saturatedFat: Double? = nil, butyricAcid: Double? = nil, caproicAcid: Double? = nil, caprylicAcid: Double? = nil, capricAcid: Double? = nil, lauricAcid: Double? = nil, myristicAcid: Double? = nil, palmiticAcid: Double? = nil, stearicAcid: Double? = nil, arachidicAcid: Double? = nil, behenicAcid: Double? = nil, lignocericAcid: Double? = nil, ceroticAcid: Double? = nil, montanicAcid: Double? = nil, melissicAcid: Double? = nil, monounsaturatedFat: Double? = nil, polyunsaturatedFat: Double? = nil, alphaLinolenicAcid: Double? = nil, eicosapentaenoicAcid: Double? = nil, docosahexaenoicAcid: Double? = nil, omega3Fat: Double? = nil, omega6Fat: Double? = nil, omega9Fat: Double? = nil, arachidonicAcid: Double? = nil, gammaLinolenicAcid: Double? = nil, dihomoGammaLinolenicAcid: Double? = nil, linoleicAcid: Double? = nil, oleicAcid: Double? = nil, transFat: Double? = nil, cholesterol: Double? = nil, elaidicAcid: Double? = nil, gondoicAcid: Double? = nil, meadAcid: Double? = nil, erucicAcid: Double? = nil, nervonicAcid: Double? = nil) {
        self.saturatedFat = saturatedFat
        self.butyricAcid = butyricAcid
        self.caproicAcid = caproicAcid
        self.caprylicAcid = caprylicAcid
        self.capricAcid = capricAcid
        self.lauricAcid = lauricAcid
        self.myristicAcid = myristicAcid
        self.palmiticAcid = palmiticAcid
        self.stearicAcid = stearicAcid
        self.arachidicAcid = arachidicAcid
        self.behenicAcid = behenicAcid
        self.lignocericAcid = lignocericAcid
        self.ceroticAcid = ceroticAcid
        self.montanicAcid = montanicAcid
        self.melissicAcid = melissicAcid
        self.monounsaturatedFat = monounsaturatedFat
        self.polyunsaturatedFat = polyunsaturatedFat
        self.alphaLinolenicAcid = alphaLinolenicAcid
        self.eicosapentaenoicAcid = eicosapentaenoicAcid
        self.docosahexaenoicAcid = docosahexaenoicAcid
        self.omega3Fat = omega3Fat
        self.omega6Fat = omega6Fat
        self.omega9Fat = omega9Fat
        self.arachidonicAcid = arachidonicAcid
        self.gammaLinolenicAcid = gammaLinolenicAcid
        self.dihomoGammaLinolenicAcid = dihomoGammaLinolenicAcid
        self.linoleicAcid = linoleicAcid
        self.oleicAcid = oleicAcid
        self.transFat = transFat
        self.cholesterol = cholesterol
        self.elaidicAcid = elaidicAcid
        self.gondoicAcid = gondoicAcid
        self.meadAcid = meadAcid
        self.erucicAcid = erucicAcid
        self.nervonicAcid = nervonicAcid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case saturatedFat
        case butyricAcid
        case caproicAcid
        case caprylicAcid
        case capricAcid
        case lauricAcid
        case myristicAcid
        case palmiticAcid
        case stearicAcid
        case arachidicAcid
        case behenicAcid
        case lignocericAcid
        case ceroticAcid
        case montanicAcid
        case melissicAcid
        case monounsaturatedFat
        case polyunsaturatedFat
        case alphaLinolenicAcid
        case eicosapentaenoicAcid
        case docosahexaenoicAcid
        case omega3Fat
        case omega6Fat
        case omega9Fat
        case arachidonicAcid
        case gammaLinolenicAcid
        case dihomoGammaLinolenicAcid
        case linoleicAcid
        case oleicAcid
        case transFat
        case cholesterol
        case elaidicAcid
        case gondoicAcid
        case meadAcid
        case erucicAcid
        case nervonicAcid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(saturatedFat, forKey: .saturatedFat)
        try container.encodeIfPresent(butyricAcid, forKey: .butyricAcid)
        try container.encodeIfPresent(caproicAcid, forKey: .caproicAcid)
        try container.encodeIfPresent(caprylicAcid, forKey: .caprylicAcid)
        try container.encodeIfPresent(capricAcid, forKey: .capricAcid)
        try container.encodeIfPresent(lauricAcid, forKey: .lauricAcid)
        try container.encodeIfPresent(myristicAcid, forKey: .myristicAcid)
        try container.encodeIfPresent(palmiticAcid, forKey: .palmiticAcid)
        try container.encodeIfPresent(stearicAcid, forKey: .stearicAcid)
        try container.encodeIfPresent(arachidicAcid, forKey: .arachidicAcid)
        try container.encodeIfPresent(behenicAcid, forKey: .behenicAcid)
        try container.encodeIfPresent(lignocericAcid, forKey: .lignocericAcid)
        try container.encodeIfPresent(ceroticAcid, forKey: .ceroticAcid)
        try container.encodeIfPresent(montanicAcid, forKey: .montanicAcid)
        try container.encodeIfPresent(melissicAcid, forKey: .melissicAcid)
        try container.encodeIfPresent(monounsaturatedFat, forKey: .monounsaturatedFat)
        try container.encodeIfPresent(polyunsaturatedFat, forKey: .polyunsaturatedFat)
        try container.encodeIfPresent(alphaLinolenicAcid, forKey: .alphaLinolenicAcid)
        try container.encodeIfPresent(eicosapentaenoicAcid, forKey: .eicosapentaenoicAcid)
        try container.encodeIfPresent(docosahexaenoicAcid, forKey: .docosahexaenoicAcid)
        try container.encodeIfPresent(omega3Fat, forKey: .omega3Fat)
        try container.encodeIfPresent(omega6Fat, forKey: .omega6Fat)
        try container.encodeIfPresent(omega9Fat, forKey: .omega9Fat)
        try container.encodeIfPresent(arachidonicAcid, forKey: .arachidonicAcid)
        try container.encodeIfPresent(gammaLinolenicAcid, forKey: .gammaLinolenicAcid)
        try container.encodeIfPresent(dihomoGammaLinolenicAcid, forKey: .dihomoGammaLinolenicAcid)
        try container.encodeIfPresent(linoleicAcid, forKey: .linoleicAcid)
        try container.encodeIfPresent(oleicAcid, forKey: .oleicAcid)
        try container.encodeIfPresent(transFat, forKey: .transFat)
        try container.encodeIfPresent(cholesterol, forKey: .cholesterol)
        try container.encodeIfPresent(elaidicAcid, forKey: .elaidicAcid)
        try container.encodeIfPresent(gondoicAcid, forKey: .gondoicAcid)
        try container.encodeIfPresent(meadAcid, forKey: .meadAcid)
        try container.encodeIfPresent(erucicAcid, forKey: .erucicAcid)
        try container.encodeIfPresent(nervonicAcid, forKey: .nervonicAcid)
    }
}

