//
// MiscellaneousNutriments.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MiscellaneousNutriments: Codable, JSONEncodable, Hashable {

    /** Caffeine measured in mg */
    public var caffeine: Double?
    /** Taurine measured in gram */
    public var taurine: Double?
    /** Nucleotides measured in <UNK> */
    public var nucleotides: Double?
    /** Fiber measured in <UNK> */
    public var fiber: Double?
    /** Alcohol measured in % vol */
    public var alcohol: Double?

    public init(caffeine: Double? = nil, taurine: Double? = nil, nucleotides: Double? = nil, fiber: Double? = nil, alcohol: Double? = nil) {
        self.caffeine = caffeine
        self.taurine = taurine
        self.nucleotides = nucleotides
        self.fiber = fiber
        self.alcohol = alcohol
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case caffeine
        case taurine
        case nucleotides
        case fiber
        case alcohol
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(caffeine, forKey: .caffeine)
        try container.encodeIfPresent(taurine, forKey: .taurine)
        try container.encodeIfPresent(nucleotides, forKey: .nucleotides)
        try container.encodeIfPresent(fiber, forKey: .fiber)
        try container.encodeIfPresent(alcohol, forKey: .alcohol)
    }
}

